name: Build Test 

on:
  pull_request:
  push:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
      fail-fast: false
    # container: osrf/ros:eloquent-desktop
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.0.25
      with:
        required-ros-distributions: eloquent
    - run: rosinstall_generator locomotion_manager --rosdistro eloquent --deps-only --deps --upstream-development > /tmp/deps.repos   

    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.0.17
      with:
        package-name: locomotion_manager 
        vcs-repo-file-url: /tmp/deps.repos

    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()