name: Build Test 

on:
  pull_request:
  push:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
      fail-fast: false
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.0.16
      with:
        required-ros-distributions: eloquent
        
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: locomotion_manager 
        vcs-repo-file-url: |
          https://raw.githubusercontent.com/ros2/ros2/eloquent/ros2.repos
          https://raw.githubusercontent.com/esa-prl/rover_repos/master/marta_simulation.repos

    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()